mod army_movement;
mod army_systems;
mod army_visuals;
mod buildings_ui;
mod camera_controls;
mod country_selection_ui;
mod diplomacy;
mod end_turn_ui;
mod game_systems;
mod lighting;
mod main_menu_ui;
mod map_generation;
mod player_country_ui;
mod province_info_ui;
mod province_visuals;
mod save_load;
mod selection;
mod setup_egui_camera;
mod terrain_visual_3d;
mod turn;

pub use army_movement::ArmyMovementPlugin;
pub use army_systems::ArmySystemsPlugin;
pub use army_visuals::ArmyRendering;
pub use buildings_ui::BuildingsUI;
pub use camera_controls::GameCamera;
pub use country_selection_ui::CountrySelectionUI;
pub use diplomacy::DiplomacyPlugin;
pub use end_turn_ui::EndTurnUI;
pub use game_systems::GameSystems;
pub use lighting::Lighting;
pub use main_menu_ui::MainMenu;
pub use map_generation::MapGenerationPlugin;
pub use player_country_ui::PlayerCountryUI;
pub use province_info_ui::ProvinceInfoUI;
pub use province_visuals::ProvinceVisualsPlugin;
pub use save_load::SaveLoadPlugin;
pub use selection::SelectionPlugin;
pub use setup_egui_camera::SetupEguiCamera;
pub use terrain_visual_3d::Terrain3DVisualsPlugin;
pub use turn::TurnPlugin;
